config/routes.rb
Rails.application.routes.draw do
  #get 'tasklists/:id', to: 'tasklists#show'
  #post 'tasklists', to: 'tasklists#create'
  #put 'tasklists/:id', to: 'tasklists#update'
  #delete 'tasklists/:id', to: 'tasklests#destroy'

  #get 'tasklists', to: 'tasklists#index'
  #get 'tasklists/new', to: 'tasklists#new'
  #get 'tasklists/:id/edit', to: 'tasklists#exit'

  root to: 'tasklists#index'
  resources :tasklists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status , presence: true, length: { maximum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  def index
    @tasklists = Tasklist.all
  end

  def show
    @tasklist = Tasklist.find(params[:id])
  end

  def new
    @tasklist = Tasklist.new
  end

  def create
    @tasklist = Tasklist.new(tasklist_params)

    if @tasklist.save
      flash[:success] = 'task が正常に登録されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'taskが登録できませんでした'
      render :new
    end

  end

  def edit
    @tasklist = Tasklist.find(params[:id])
  end

  def update
    @tasklist = Tasklist.find(params[:id])

    if @tasklist.update(tasklist_params)
      flash[:success] = 'Taskは正常に更新されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'Taskは更新できませんでした'
      render :edit
    end
  end

  def destroy
    @tasklist = Tasklist.find(params[:id])
    @tasklist.destroy

    flash[:success] = 'Taskは正常に削除されました'
    redirect_to tasklists_url
  end


  private
  def tasklist_params
    params.require(:tasklist).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do | message_type, task | %>
  <div><%= task %>></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasklists/_form.html.erb
<%= form_for(tasklist) do |f| %>
  <% if tasklist.errors.any? %>
    <div id="error_explanation">
       <ul>
          <% tasklist.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
       </ul>
    </div>
  <% end %>

  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>
  <%= f.label :status, 'ステータス' %>
  <%= f.select :status, { 起票: 1, 作業中: 2, 完了: 3 } %>
  
  <%= f.submit '登録' %>
<% end %>

app/views/tasklists/edit.html.erb
<h1>id:<%= @tasklist.id %>のタスク編集ページ</h1>

<%= render 'form', tasklist: @tasklist %>

<%= link_to '一覧に戻る' , tasklists_path %>

app/views/tasklists/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasklists.each do |task| %>
    <li><%= link_to task.id, task %>:<%= task.content %> &gt; <%= task.status %></li>
  <% end %>
</ul>

<%= link_to '新規タスクの登録', new_tasklist_path %>

app/views/tasklists/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', tasklist: @tasklist %>

<%= link_to '一覧に戻る' , tasklists_path %>

app/views/tasklists/show.html.erb
<h1>id:<%= @tasklist.id %>のタスク詳細ページ</h1>

<p>タスク：<%= @tasklist.content %></p>
<p>ステータス：<%= @tasklist.status %></p>

<%= link_to '一覧に戻る', tasklists_path %>
<%= link_to 'このタスクを編集する' , edit_tasklist_path(@tasklist) %>
<%= link_to 'このタスクを削除する' , @tasklist , method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>